### ISSUE TITLE
reformat by removing error E713 for membership test

### ISSUE THREAD

**Issue by 3c2b2ff5** [google/nsscache#103]
currently the following syntax is in `ldapsource.py` and `httpsource.py`:
```
if not x in y
```
This should be:
```
if x not in y:
```
I think error E111, E114 related to indentation is not relevant, since nsscache is following google style guide by having only 2 spaces as indentation instead of 4.

**Comment by 3c2b2ff5** [comment]
It seems google is using now indentation of 4 spaces, should I apply this as well?
Further more should I format with yapf?

**Comment by jaqx0r** [comment]
Yes, please use yapf to format.

When this code was first opened, Google used 2 space indents.  I only found
out when I set up yapf last week that it's now 4 :)

I personally don't mind what it is (especially now yapf is set to use 2
space indents in this project config, and I like formatters because now I
don't have to think about it)  but if you want to change it to 4, let's do
it on all files at once with no other changes.

**Comment by 3c2b2ff5** [comment]
cool. Will do and use 4 spaces instead of 2, since this is now the standard for google as well as for Python. Then I'll reformat with yapf.

**Comment by 3c2b2ff5** [comment]
> with no other changes

do you mean the if statements I mentioned?

**Comment by jaqx0r** [comment]
yeah I think the changes will be lost in the noise, I expect there'll be a
massive diff, and I like having easy to read change history so that one day
a future explorer can figure out why the code looks like it does.  Having a
reformatting change blended into a code change makes it tricky to see the
two changes.

So yes please, send me one PR for the if statements, and a second for the
reformatting.

**Comment by 3c2b2ff5** [comment]
cool

**Comment by 3c2b2ff5** [comment]
can be closed. will make further tests and report if any occurs.
